joint_limits:
  j1_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: true
    max_jerk: 120.0
    has_position_limits: true
    min_position: -1.865
    max_position: 2.365

  j2_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: true
    max_jerk: 120.0
    has_position_limits: true
    min_position: 0.0
    max_position: 1.85

  j3_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: true
    max_jerk: 120.0
    has_position_limits: true
    min_position: 0.0
    max_position: 2.13861

  j4_joint:
    has_velocity_limits: true
    max_velocity: 20.0
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 120.0
    has_position_limits: true
    min_position: -3.14159265358979
    max_position: 3.14159265358979
